### ISSUE TITLE
Plotting PCA decomposition

### ISSUE THREAD

**Issue by pburdet** [vidartf/hyperspyUI#11]
I was expecting the `explore decomposition` to work as `plot_decomposition_result`. What does `explore decomposition` do exactly? `plot_decomposition_result` doesn't need extra computation, it would be nice to have it (maybe keeping only the two signal windows a slider)

**Comment by vidartf** [comment]
Yeah, I wasn't really able to come up with an intuitive name for that one. It is a lot easier to understand if you use it on an image than a spectrum (mainly due to lack of spectrum legend). What it does is show the ```get_decomposition_model``` for ```n``` components and the residual of that model compared to the original data. For utility it also shows the factor of component ```n```. Again, try it out on a 2D image, and hopefully it will make more sense.

**Comment by vidartf** [comment]
It is mostly useful when it is not so easy to determine how many components to use (or if PCA is OK to use), as the residual shows pretty clearly what gets left out.

**Comment by pburdet** [comment]
I get it. Nice. Do you plan to have `plot_decomposition_model`? Faster and probably more memory efficient

**Comment by vidartf** [comment]
I don't really make much plan for features, I normally add them when I need them :) My goal was to try and make the UI code so easy that anybody that knows hyperspy can add new features quickly. That being said, it should just be a couple of lines of code. Please have a look at this commit (where I implemented this feature) as a quick guide for how to add new actions to existing plugins: 7f1c2d05ed944232770c0bad81ae6db6b5158f63 (check out the DEV-README.txt if unsure about something).
